image: docker:latest
services:
  - name: docker:dind
    alias: docker


stages:
  - build
  - Test acceptation
  - Release image
  - Deploy staging
  - Deploy prod

docker-build:
  # Use the official docker image.
  stage: build
  script:
    - docker build -t  alpinehelloworld .
    - docker save alpinehelloworld > alpinehelloworld.tar
  artifacts:
    paths:
      - alpinehelloworld.tar    


test acceptation:
  # Official docker image.
  stage: Test acceptation
  script:
    - docker load < alpinehelloworld.tar
    - docker run -d -p 80:5000 -e PORT=5000 --name webapp alpinehelloworld
    - sleep 5
    - apk --no-cache add curl
    - curl "http://docker" | grep  "Hello world!"

release image:
  stage: Release image
  script:
    - docker load < alpinehelloworld.tar
    - docker tag alpinehelloworld "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker tag alpinehelloworld "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"

deploy staging:
  stage: Deploy staging
  environment:
    name: staging
    url: https://eazytraining-staging-9839de32fe85.herokuapp.com # eg: url_a_recuperer_sur_heroku
  only:
    - master
  script:
    - apk --no-cache add npm
    - npm i -g heroku@7.68.0
    - heroku container:login
    - heroku create eazytraining-staging || echo "project already exist"
    - heroku container:push -a eazytraining-staging web
    - heroku container:release -a eazytraining-staging web

deploy prod:
  stage: Deploy prod
  environment:
    name: prod
    url: https://eazytraining-prod-70584e6ff38a.herokuapp.com # eg: url_a_recuperer_sur_heroku
  only:
    - master
  script:
    - apk --no-cache add npm
    - npm i -g heroku@7.68.0
    - heroku container:login
    - heroku create eazytraining-prod  || echo "project already exist"
    - heroku container:push -a eazytraining-prod web
    - heroku container:release -a eazytraining-prod web    